CREATE SCHEMA NMR;

CREATE TABLE MATCHCOUNTRY(
	COUNTRY_ID VARCHAR(36),
	COUNTRYNAME VARCHAR(50),
	PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE MATCHCATEGORY(
	CATEGORY_ID VARCHAR(36),
	CATEGORYNAME VARCHAR(36),
	PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE TEAMINFO(
	TEAM_ID VARCHAR(36),
	TEAMNAME VARCHAR(36),
	COUNTRY_ID VARCHAR(36),
	PRIMARY KEY (TEAM_ID)
);

ALTER TABLE TEAMINFO ADD CONSTRAINT TEAM_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES MATCHCOUNTRY(COUNTRY_ID);

CREATE TABLE MATCHINFO(
	MATCH_ID VARCHAR(36),
	HOMETEAM_ID VARCHAR(36),
	GUESTTEAM_ID VARCHAR(36),
	COUNTRY_ID VARCHAR(36),
	CATEGORY_ID VARCHAR(36),
	MATCHROUND NUMERIC(3, 0),
	MATCHTIME TIMESTAMP,
	PRIMARY KEY (MATCH_ID)
);

ALTER TABLE MATCHINFO ADD CONSTRAINT HOMETEAM_TEAM FOREIGN KEY (HOMETEAM_ID) REFERENCES TEAMINFO(TEAM_ID);

ALTER TABLE MATCHINFO ADD CONSTRAINT GUESTTEAM_TEAM FOREIGN KEY (GUESTTEAM_ID) REFERENCES TEAMINFO(TEAM_ID);

ALTER TABLE MATCHINFO ADD CONSTRAINT MATCHCOUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES MATCHCOUNTRY(COUNTRY_ID);

ALTER TABLE MATCHINFO ADD CONSTRAINT MATCHINFO_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MATCHCATEGORY(CATEGORY_ID);


