INSERT INTO MATCHCOUNTRY(COUNTRY_ID, COUNTRYNAME) VALUES('zh','China');

INSERT INTO MATCHCATEGORY(CATEGORY_ID, CATEGORYNAME) VALUES('csl', 'Chinese Super League');

INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('SH', '上海申花', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('HD', '广州恒大', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('TH', '天津天海', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('DL', '大连一方', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('JY', '河南建业', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('FL', '广州富力', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('SG', '上海上港', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('TT', '天津泰达', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('LN', '山东鲁能', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('RH', '北京人和', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('CX', '重庆斯威', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('GA', '北京国安', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('HX', '河北华夏', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('JS', '江苏苏宁', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('SZ', '深圳佳兆业', 'zh');
INSERT INTO TEAMINFO(TEAM_ID, TEAMNAME, COUNTRY_ID) VALUES('WH', '武汉卓尔', 'zh');
